services:
  rabbitmq:
    image: rabbitmq:4.0.4-management-alpine
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - area_network
    volumes:
      - ./rabbit-mq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
    healthcheck:
      test: [ "CMD", "rabbitmqctl", "status" ]
      interval: 5s
      timeout: 15s
      retries: 5
    restart: always
    profiles: [ "server", "web", "mobile", "full" ]

  mariadb:
    image: mariadb:11.4.4
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_HOST: "%"
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./server/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - area_network
    healthcheck:
      test: [ "CMD", "mariadb-admin", "ping", "-h", "localhost", "-u", "root", "-p${DB_PASSWORD}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    env_file:
      - .env
    restart: always
    profiles: [ "server", "web", "mobile", "full" ]

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./server:/app:rw
      - ./ssl:/app/ssl:ro
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_NAME: ${DB_NAME}
      DB_PASSWORD: ${DB_PASSWORD}
      AIR_FORCE: "true"
    depends_on:
      mariadb:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - area_network
    env_file:
      - server/.env
    restart: always
    healthcheck:
      test: [ "CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s
    profiles: [ "server", "web", "mobile", "full" ]

#  server-action-consumer:
#    build:
#      context: ./server
#      dockerfile: Dockerfile_action_consumer
#    volumes:
#      - ./server:/app:rw
#      - ./ssl:/app/ssl:ro
#    environment:
#      DB_HOST: ${DB_HOST}
#      DB_PORT: ${DB_PORT}
#      DB_USER: ${DB_USER}
#      DB_NAME: ${DB_NAME}
#      DB_PASSWORD: ${DB_PASSWORD}
#    depends_on:
#      mariadb:
#        condition: service_healthy
#      rabbitmq:
#        condition: service_healthy
#      server:
#        condition: service_healthy
#    networks:
#      - area_network
#    env_file:
#      - server/.env
#    restart: always
#    profiles: [ "server", "web", "mobile", "full" ]
#
#  server-reaction-consumer:
#    build:
#      context: ./server
#      dockerfile: Dockerfile_reaction_consumer
#    volumes:
#      - ./server:/app:rw
#      - ./ssl:/app/ssl:ro
#    environment:
#      DB_HOST: ${DB_HOST}
#      DB_PORT: ${DB_PORT}
#      DB_USER: ${DB_USER}
#      DB_NAME: ${DB_NAME}
#      DB_PASSWORD: ${DB_PASSWORD}
#    depends_on:
#      mariadb:
#        condition: service_healthy
#      rabbitmq:
#        condition: service_healthy
#      server:
#        condition: service_healthy
#    networks:
#      - area_network
#    env_file:
#      - server/.env
#    restart: always
#    profiles: [ "server", "web", "mobile", "full" ]

  client_mobile:
    build:
      context: ./client_mobile
      dockerfile: Dockerfile
      args:
        - API_URL
        - WEB_CLIENT_URL
        - MOBILE_CLIENT_URL
        - GITHUB_CLIENT_ID
        - GITHUB_CLIENT_SECRET
    volumes:
      - mobile_builds:/app/build/app/outputs/flutter-apk
    networks:
      - area_network
    env_file:
      - ./client_mobile/.env
    profiles: [ "mobile", "full" ]
    depends_on:
      server:
        condition: service_healthy
    restart: "no"

  client_web:
    build:
      context: ./client_web
      dockerfile: Dockerfile
      args:
        - VITE_PORT
        - VITE_ENDPOINT
        - VITE_GOOGLE_CLIENT_ID
        - VITE_GOOGLE_CLIENT_SECRET
        - VITE_MICROSOFT_CLIENT_ID
        - VITE_LINKEDIN_CLIENT_ID
        - VITE_LINKEDIN_CLIENT_SECRET
        - VITE_SPOTIFY_CLIENT_ID
        - VITE_SPOTIFY_CLIENT_SECRET
        - API_URL
        - WEB_CLIENT_URL
        - MOBILE_CLIENT_URL
        - GITHUB_CLIENT_ID
        - GITHUB_CLIENT_SECRET
    ports:
      - "${VITE_PORT}:${VITE_PORT}"
    volumes:
      - mobile_builds:/usr/share/nginx/html/mobile_builds:ro
    depends_on:
      server:
        condition: service_healthy
      client_mobile:
        condition: service_completed_successfully
        required: false # TODO: remove before final defense
    networks:
      - area_network
    env_file:
      - ./client_web/.env
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "wget --no-verbose --tries=1 --spider --no-check-certificate https://localhost:${VITE_PORT} || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    profiles: [ "web", "full" ]

  server-healthcheck:
    image: alpine:3.20.3
    depends_on:
      mariadb:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      server:
        condition: service_healthy
    profiles: [ "server" ]
    restart: "no"

  web-healthcheck:
    image: alpine:3.20.3
    depends_on:
      mariadb:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      server:
        condition: service_healthy
      client_web:
        condition: service_healthy
    environment:
      - VITE_PORT=${VITE_PORT}
    profiles: [ "web" ]
    restart: "no"

  mobile-healthcheck:
    image: alpine:3.20.3
    depends_on:
      mariadb:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      server:
        condition: service_healthy
      client_mobile:
        condition: service_completed_successfully
    profiles: [ "mobile" ]
    restart: "no"

  full-healthcheck:
    image: alpine:3.20.3
    depends_on:
      mariadb:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      server:
        condition: service_healthy
      client_web:
        condition: service_healthy
      client_mobile:
        condition: service_completed_successfully
    environment:
      - VITE_PORT=${VITE_PORT}
    profiles: [ "full" ]
    restart: "no"

volumes:
  mobile_builds:
  mariadb_data:


networks:
  area_network:
    driver: bridge
