services:
  area-client-mobile:
    build:
      context: ./client_mobile
      dockerfile: Dockerfile
      args:
        - VITE_PORT
        - VITE_ENDPOINT
        - VITE_GOOGLE_CLIENT_ID
        - VITE_GOOGLE_CLIENT_SECRET
        - VITE_MICROSOFT_CLIENT_ID
        - VITE_LINKEDIN_CLIENT_ID
        - VITE_LINKEDIN_CLIENT_SECRET
        - VITE_SPOTIFY_CLIENT_ID
        - VITE_SPOTIFY_CLIENT_SECRET
        - API_URL
        - WEB_CLIENT_URL
        - MOBILE_CLIENT_URL
        - GITHUB_CLIENT_ID
        - GITHUB_CLIENT_SECRET
    volumes:
      - area-client-data:/app/build/app/outputs/flutter-apk
    networks:
      - area-network
    env_file:
      - ./client_mobile/.env.mobile

  area-client-web:
    build:
      context: ./client_web
      dockerfile: Dockerfile
      args:
        - VITE_PORT
        - VITE_ENDPOINT
        - VITE_GOOGLE_CLIENT_ID
        - VITE_GOOGLE_CLIENT_SECRET
        - VITE_MICROSOFT_CLIENT_ID
        - VITE_LINKEDIN_CLIENT_ID
        - VITE_LINKEDIN_CLIENT_SECRET
        - VITE_SPOTIFY_CLIENT_ID
        - VITE_SPOTIFY_CLIENT_SECRET
        - API_URL
        - WEB_CLIENT_URL
        - MOBILE_CLIENT_URL
        - GITHUB_CLIENT_ID
        - GITHUB_CLIENT_SECRET
    ports:
      - "${VITE_PORT}:${VITE_PORT}"
    volumes:
      - area-client-data:/usr/share/nginx/html/mobile_builds
    depends_on:
      - area-client-mobile
    networks:
      - area-network
    env_file:
      - ./client_web/.env.local

volumes:
  area-client-data:


networks:
  area-network:
