services:
  area-client-web:
    build:
      target: development
    volumes:
      - ./client_web:/app
      - /app/node_modules
      - ssl-certs:/app/certs
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true

  area-server:
    build:
      target: development
    volumes:
      - ./server:/app
      - go-modules:/go/pkg/mod
    environment:
      - GO_ENV=development

  area-server-action-consumer:
    build:
      target: development
    volumes:
      - ./server:/app
      - go-modules:/go/pkg/mod
    environment:
      - GO_ENV=development

  area-server-reaction-consumer:
    build:
      target: development
    volumes:
      - ./server:/app
      - go-modules:/go/pkg/mod
    environment:
      - GO_ENV=development

volumes:
  ssl-certs:
  go-modules:
