services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "8080:15672"
      - "5000:5673"
    networks:
      - rabbitmq_network
    volumes:
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
    healthcheck:
      test: [ "CMD", "rabbitmqctl", "status" ]
      interval: 5s
      timeout: 15s
      retries: 5

networks:
    rabbitmq_network:
        driver: bridge
