name: client_mobile
description: Area app

publish_to: 'none'

version: 0.0.1+1

environment:
  sdk: ^3.1.1

dependencies:
  flutter:
    sdk: flutter

  english_words: ^4.0.0
  provider: ^6.0.0
  flutter_appauth: ^8.0.3
  go_router: ^14.6.2
  flutter_dotenv: ^5.2.1
  flutter_secure_storage: ^9.2.3
  http: ^1.2.2
  flutter_web_auth: ^0.6.0
  google_sign_in: ^6.2.2
  aad_oauth: ^1.0.1
  flutter_inappwebview: ^6.1.5
  crypto: ^3.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/
